version: '3'

services:
  # app:
  #   build: .
  #   environment:
  #     MONGO_URI: mongodb://admin:root@mongo:27017/admin

  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
  
  redis:
    image: redis
    container_name: redis-cache
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/usr/local/etc/redis/redis.conf

volumes:
  mongo-volume:
  redis-volume: